# Operations on NumPy Arrays



### Manipulating Arrays

Let's look at some ways to manipulate arrays, i.e. changing the shape, combining and splitting arrays, etc.   

#### Reshaping Arrays

Reshaping is done using the ```reshape()``` function.


In [8]:
import numpy as np

# Reshape a 1-D array to a 3 x 4 array
some_array = np.arange(10,22).reshape(3, 4)
print(some_array)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [12]:
print(some_array[0,-2:])

[12 13]


In [14]:
print(some_array[:,1])

[11 15 19]


In [16]:
print(some_array[0:2,-2:])

[[12 13]
 [16 17]]


In [17]:
some_array.shape

(3, 4)

In [18]:
# Can reshape it further 
some_array.reshape(2, 6)

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

In [19]:
some_array.reshape(4,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [25]:
# If you specify -1 as a dimension, the dimensions are automatically calculated
# -1 means "whatever dimension is needed" 
some_array.reshape(6, -1)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

```array.T``` returns the transpose of an array.

In [27]:
some_array

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [26]:
# Transposing an array
some_array.T

array([[10, 14, 18],
       [11, 15, 19],
       [12, 16, 20],
       [13, 17, 21]])

### Stacking and Splitting Arrays

#### Stacking: ```np.hstack()``` and ```n.vstack()```

Stacking is done using the ```np.hstack()``` and ```np.vstack()``` methods. For horizontal stacking, the number of rows should be the same, while for vertical stacking, the number of columns should be the same.

In [28]:
# Creating two arrays
array_1 = np.arange(12).reshape(3, 4)
array_2 = np.arange(20).reshape(5, 4)

print(array_1)
print("\n")
print(array_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
# vstack
# Note that np.vstack(a, b) throws an error - you need to pass the arrays as a list
np.vstack((array_1, array_2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [29]:
array_1 = np.arange(12).reshape(4, 3)
array_2 = np.arange(20).reshape(4, 5)

print(array_1)
print("\n")
print(array_2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [31]:
np.hstack((array_1,array_2))

array([[ 0,  1,  2,  0,  1,  2,  3,  4],
       [ 3,  4,  5,  5,  6,  7,  8,  9],
       [ 6,  7,  8, 10, 11, 12, 13, 14],
       [ 9, 10, 11, 15, 16, 17, 18, 19]])

Similarly, two arrays having the same number of rows can be horizontally stacked using ```np.hstack((a, b))```.

### Perform Operations on Arrays

Performing mathematical operations on arrays is extremely simple. Let's see some common operations.


#### Basic Mathematical Operations

NumPy provides almost all the basic math functions - exp, sin, cos, log, sqrt etc. The function is applied to each element of the array.


In [33]:
# Basic mathematical operations
a = np.arange(1, 20)

# sin, cos, exp, log
print("Sin ", np.sin(a))
print("Cos ", np.cos(a))
print("Exp ", np.exp(a))
print("Log ", np.log(a))

Sin  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725
  0.14987721]
Cos  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396
  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334  0.66031671
  0.98870462]
Exp  [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06
 2.41549528e+07 6.56599691e+07 1.78482301e+08]
Log  [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176
 2.94443898]


#### Apply User Defined Functions

You can also apply your own functions on arrays. For e.g. applying the function ```x/(x+1)``` to each element of an array.

One way to do that is by looping through the array, which is the non-numpy way. You would rather want to write **vectorised code**. 

The simplest way to do that is to vectorise the function you want, and then apply it on the array. Numpy provides the ```np.vectorize()``` method to vectorise functions.

Let's look at both the ways to do it.

In [34]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [37]:
# The non-numpy way, not recommended
a_list = [x/(x+1) for x in a]
print(a_list)

[0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.8888888888888888, 0.9, 0.9090909090909091, 0.9166666666666666, 0.9230769230769231, 0.9285714285714286, 0.9333333333333333, 0.9375, 0.9411764705882353, 0.9444444444444444, 0.9473684210526315, 0.95]


In [44]:
# The numpy way: vectorize the function, then apply it
f = np.vectorize(lambda x: x/(x+1))
f(a)
# f(arr)
# f(b)
# f(array_1)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])

In [45]:
# Apply function on a 2-d array: Applied to each element 
b = np.linspace(1, 100, 10).reshape(2,5)
f(b)

array([[0.5       , 0.92307692, 0.95833333, 0.97142857, 0.97826087],
       [0.98245614, 0.98529412, 0.98734177, 0.98888889, 0.99009901]])

This also has the advantage that you can vectorize the function once, and then apply it as many times as needed. 

#### Apply Basic Linear Algebra Operations

NumPy provides the ```np.linalg``` package to apply common linear algebra operations, such as:
* ```np.linalg.inv```: Inverse of a matrix
* ```np.linalg.det```: Determinant of a matrix
* ```np.linalg.eig```: Eigenvalues and eigenvectors of a matrix
    
Also, you can multiple matrices using ```np.dot(a, b)```. 


In [ ]:
# np.linalg documentation
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

In [66]:
# Creating arrays
a = np.arange(1, 10).reshape(3, 3)
b= np.arange(1, 13).reshape(3, 4)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [51]:
help(np.linalg.inv)

Help on function inv in module numpy.linalg:

inv(a)
    Compute the (multiplicative) inverse of a matrix.
    
    Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Matrix to be inverted.
    
    Returns
    -------
    ainv : (..., M, M) ndarray or matrix
        (Multiplicative) inverse of the matrix `a`.
    
    Raises
    ------
    LinAlgError
        If `a` is not square or inversion fails.
    
    See Also
    --------
    scipy.linalg.inv : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    Examples
    --------
    >>> from numpy.linalg import inv
    >>> a = np.array([[1., 2.], [3., 4.]])
    >>> ainv = inv(a)
    >>> np.allclose(np.dot(a, ainv), np.eye(2))
    True
    >>> np.allclose(np.dot(ainv, a), 

In [61]:
a = np.array([[2,4,6,7],[6,5,9,8],[3,1,7,8],[6,7,4,1]])

In [62]:
# Inverse
print(np.linalg.inv(a))

[[-0.18181818 -1.54545455  1.58181818  0.98181818]
 [ 0.27272727 -0.18181818 -0.07272727  0.12727273]
 [-0.27272727  3.18181818 -2.72727273 -1.72727273]
 [ 0.27272727 -2.18181818  1.92727273  1.12727273]]


In [63]:
# Determinant
np.linalg.det(a)

-54.999999999999964

In [64]:
# Eigenvalues and eigenvectors
np.linalg.eig(a)

(array([20.52468869+0.j        , -4.44772803+0.j        ,
        -0.53848033+0.55904045j, -0.53848033-0.55904045j]),
 array([[ 0.44668841+0.j        ,  0.4787601 +0.j        ,
          0.44238261-0.16487646j,  0.44238261+0.16487646j],
        [ 0.64831989+0.j        , -0.04905912+0.j        ,
         -0.09098143+0.18347544j, -0.09098143-0.18347544j],
        [ 0.41613091+0.j        ,  0.41746559+0.j        ,
         -0.69571461+0.j        , -0.69571461-0.j        ],
        [ 0.45495698+0.j        , -0.77078171+0.j        ,
          0.50105806-0.00972234j,  0.50105806+0.00972234j]]))

In [67]:
# Multiply matrices
np.dot(a, b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])

In [ ]:
Description
Horizontally stack two arrays using hstack, and finally, vertically stack the resultant array with the third array.

Example:
Input 1:
[[1, 2],
 [5, 6]]

[[3, 4],
 [7, 8]]

[[9, 10, 11, 12]]
Output 1:
[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 12]]

In [70]:
arr1 = np.array([[1, 2],[5, 6]])
arr2 = np.array([[3, 4],[7, 8]])
arr3 = np.array([[9, 10, 11, 12]])

arrh = np.hstack((arr1,arr2))

arrv = np.vstack((arrh,arr3)) 
print(arrv)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
Given an array, 'array_3' divide each element with 5. 
Hint: Create a vectorized function, then apply it to the array_3.

In [71]:

f = np.vectorize(lambda x:x/5)

f(arrv)

array([[0.2, 0.4, 0.6, 0.8],
       [1. , 1.2, 1.4, 1.6],
       [1.8, 2. , 2.2, 2.4]])